### ISSUE TITLE
Performance Endpoint Keywords... several 404...

### ISSUE THREAD

**Issue by PatchworkBoy** [SamJukesData/EduPowerQuery#1]
Hi Sam... The following keywords are all throwing 404 errors for me at the moment via _PerformanceTables Data.m_

- KS4UNDERLYING
- KS5UNDERLYING
- KS5APPR
- KS5MATHSCI
- SPENDPERPUPILGROUPED
- SPENDPERPUPILFULL

Not sure whether this is permanent or temporary, but these sets appear not to be downloadable as CSV, only as XLS, so would need URL structure altering in the sample query.

This appears to work... and will prompt the user to expand out the desired table from within the workbook:

```
let
    // Get the data from Performce Tables
    YearRef = if Date.Month(DateTime.LocalNow()) >= 9 then Date.Year(DateTime.LocalNow()) - 1 else Date.Year(DateTime.LocalNow()) - 2,
    
    // Change this to get different datasets
    Keyword = "KS4UNDERLYING",

    // Create URL for previous academic year
    // Edit uppercase keyword after &filters= to get different types of data
    MainURL = "https://www.compare-school-performance.service.gov.uk/download-data?download=true&regions=0&filters=" & Keyword & "&fileformat=xls&year=" & Text.From(YearRef)&"-"&Text.From(YearRef + 1) & "&meta=false",
    
    // Create URL for academic year two years ago
    // Edit uppercase keyword after &filters= to get different types of data
    BackupURL = "https://www.compare-school-performance.service.gov.uk/download-data?download=true&regions=0&filters=" & Keyword & "&fileformat=xls&year=" & Text.From(YearRef - 1)&"-"&Text.From(YearRef) & "&meta=false",
    
    // Attempt to get data from MainURL
    ErrorValue = Value.Metadata(Web.Contents(MainURL, [ManualStatusHandling={404}]))[Response.Status],
    
    // If no data found at MainURL get data from BackupURL
    Source = if ErrorValue = 404 then Excel.Workbook(Web.Contents(BackupURL)) else Excel.Workbook(Web.Contents(MainURL))
in
    Source

```

**Comment by SamJukesData** [comment]
Hi @PatchworkBoy thanks for the heads up! My bad, the sources I tested with were available in CSV format but I forgot about the results sheets having mulitple tabs so couldn't be anything but XLS. 

Nice work on the fix, we both came up with the same solution!

**Comment by SamJukesData** [comment]
Hi @PatchworkBoy thanks for the heads up! My bad, the sources I tested with were available in CSV format but I forgot about the results sheets having mulitple tabs so couldn't be anything but XLS. 

Nice work on the fix, we both came up with the same solution!
